#page title
page_title                                : StrymTV                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : StrymTV                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Powerful M3U playlist player for iOS.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sebastian Barajas                                
your_link                                 : https://twitter.com/SebasBarajasc
your_city                                 :                                 
email_address                             : strymtvapp@gmail.com
facebook_username                         :                                           
instagram_username                        : strymtvapp
twitter_username                          : Strymtvapp
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Unlimited Playlists
    description                           : Import unlimited remote and local M3U playlists to your iOS device.
    fontawesome_icon_name                 : list-alt

  - title                                 : Built-in Powerful Media Player
    description                           : Multiple Video Format Suppported - HTTP , HSL , M3U8 , MMS , RTSP , TS , MPEGTS and more.
    fontawesome_icon_name                 : play-circle

  - title                                 : Auto Update Playlists
    description                           : Auto update remote playlists.
    fontawesome_icon_name                 : sync
       
  - title                                 : Favorites List
    description                           : Add any channel or stream to favorites.
    fontawesome_icon_name                 : star
    
  - title                                 : URL Scheme
    description                           : Link directly to play any video or audio file by opening the next link in a web browser or linking service. strymtv://player/<VIDEO LINK>
    fontawesome_icon_name                 : link
     
  - title                                 : Continuous Updates
    description                           : We are continuously working to improve the app, if you have some idea or feedback send us an email at strymtvteam@gmail.com and we will get back to you.
    fontawesome_icon_name                 : gift

  - title                                 : #iPhone Device Preview
    description                           : #Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : #mobile

  - title                                 : #Easy to Tweak
    description                           : #Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #adjust

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#00ffffff"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman
